import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createClient } from '@supabase/supabase-js';
import { signInWithTestSession } from './helpers/auth-session.mjs';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const credentials={admin:['ADMIN'],office:['OFFICE'],officeB:['OFFICE_B'],operations:['OPERATIONS'],staffA:['STAFF_A'],staffB:['STAFF_B'],staffZero:['STAFF_ZERO']};
for(const [name,[code]] of Object.entries(credentials)) credentials[name]=[process.env[`KSS_TEST_${code}_EMAIL`],process.env[`KSS_TEST_${code}_PASSWORD`]];
async function signed(name){const c=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {error}=await signInWithTestSession(c,{email:credentials[name][0],password:credentials[name][1]});assert.ifError(error);return c;}
async function rpc(c,name,args={}){const {data,error}=await c.rpc(name,args);assert.ifError(error,`${name}: ${error?.message}`);return data;}
const content=(label)=>[{title:`Module ${label}`,pages:[{title:'First page',blocks:[{type:'paragraph',text:`Synthetic ${label} first page`}]},{title:'Second page',blocks:[{type:'paragraph',text:`Synthetic ${label} second page`}]}]}];
const request=()=>crypto.randomUUID();

test('TASK-20C exact-version assignments and factual learning progress',{timeout:240000},async()=>{
 assert.ok(url?.includes('dnfhkmmnlbiabqypclqg'),'literal synthetic Dev target');
 assert.ok(key&&Object.values(credentials).every(([e,p])=>e&&p));
 const [admin,office,officeB,operations,staffA,staffB,staffZero]=await Promise.all(Object.keys(credentials).map(signed));
 const anon=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 const personA='10000000-0000-4000-8000-000000000003',personB='10000000-0000-4000-8000-000000000004',personZero='10000000-0000-4000-8000-000000000008',officePerson='10000000-0000-4000-8000-000000000002';
 assert.equal((await rpc(admin,'training_assigner_access')).assigner,false,'Super role alone cannot assign');
 assert.ok((await admin.rpc('training_assign',{p_person:personA,p_course:crypto.randomUUID(),p_version:crypto.randomUUID(),p_due:'2026-11-10',p_reason:'Synthetic grant denial proof',p_request:request()})).error);
 assert.ok((await office.rpc('training_assign',{p_person:personA,p_course:crypto.randomUUID(),p_version:crypto.randomUUID(),p_due:'2026-11-10',p_reason:'Synthetic grant denial proof',p_request:request()})).error);
  assert.ok((await officeB.rpc('training_assignments_admin')).error,'ungranted Office denied');
 assert.ok((await officeB.rpc('training_assigner_candidates')).error,'ungranted Office cannot enumerate grant candidates');
 assert.ok((await operations.rpc('training_assignments_admin')).error,'Operations denied');
 assert.ok((await operations.rpc('training_my_learning')).error,'Operations denied own learning view');
 assert.ok((await anon.rpc('training_my_learning')).error,'anonymous denied');
  assert.ok((await staffA.from('training_assignments').select('id')).error,'direct Staff table read denied');
 assert.ok((await staffA.from('training_page_marks').select('assignment_id')).error,'direct marker read denied');
 assert.ok((await office.from('training_assignments').insert({person_id:personA})).error,'direct Office table write denied');
 const grant=await rpc(admin,'training_assigner_grant',{p_person:officePerson,p_from:new Date(Date.now()-60_000).toISOString(),p_until:null,p_reason:'Synthetic 20C assignment authority proof'});
 assert.equal((await rpc(office,'training_assigner_access')).assigner,true);
 assert.ok((await rpc(admin,'training_assigner_grants_read')).some(g=>g.id===grant));
 try {
  const course=await rpc(office,'training_create_course',{p_title:`Synthetic 20C exact version ${Date.now()}`,p_summary:'Synthetic assignment proof only',p_content:content('v1')});
  const v1=(await rpc(office,'training_admin',{p_course:course}))[0];
  await rpc(office,'training_publish',{p_version:v1.versionId,p_revision:1});
  const assignArgs={p_person:personA,p_course:course,p_version:v1.versionId,p_due:'2026-11-10',p_reason:'Synthetic Staff A exact v1 learning proof',p_request:request()};
  const a1=await rpc(office,'training_assign',assignArgs);
  assert.equal(await rpc(office,'training_assign',assignArgs),a1,'exact replay returns same assignment');
  assert.ok((await office.rpc('training_assign',{...assignArgs,p_due:'2026-11-11'})).error,'changed-payload replay denied');
  assert.ok((await office.rpc('training_assign',{...assignArgs,p_request:request()})).error,'duplicate active denied');
  assert.equal((await rpc(staffA,'training_my_learning')).find(a=>a.id===a1).versionId,v1.versionId);
  assert.equal((await rpc(staffA,'training_assignment_content',{p_assignment:a1})).marks.length,0,'opening content writes no marker');
  await rpc(staffA,'training_save_place',{p_assignment:a1,p_module:1,p_page:1});
  await rpc(staffA,'training_mark_page',{p_assignment:a1,p_module:1,p_page:1});
  await rpc(staffA,'training_mark_page',{p_assignment:a1,p_module:1,p_page:1});
  assert.equal((await rpc(staffA,'training_my_learning')).find(a=>a.id===a1).viewedCount,1,'mark idempotent');
  assert.ok((await staffB.rpc('training_assignment_content',{p_assignment:a1})).error,'other Staff guessed ID denied');
  assert.ok((await staffB.rpc('training_assignment_history',{p_assignment:a1})).error,'other Staff history denied');
  assert.ok((await officeB.rpc('training_assignment_history',{p_assignment:a1})).error,'ungranted Office history denied');
  assert.ok((await operations.rpc('training_assignment_history',{p_assignment:a1})).error,'Operations history denied');
  assert.ok((await anon.rpc('training_assignment_content',{p_assignment:a1})).error,'anonymous content denied');
  assert.ok((await staffB.rpc('training_mark_page',{p_assignment:a1,p_module:1,p_page:2})).error,'other Staff write denied');
  assert.ok((await staffA.rpc('training_mark_page',{p_assignment:a1,p_module:2,p_page:1})).error,'invalid module denied');
  const dueEarlier=await rpc(office,'training_change_due',{p_assignment:a1,p_revision:1,p_due:'2026-10-20',p_reason:'Synthetic earlier due date correction',p_request:request()});
  assert.equal(dueEarlier,a1);
  await rpc(office,'training_change_due',{p_assignment:a1,p_revision:2,p_due:'2026-12-20',p_reason:'Synthetic later due date correction',p_request:request()});
  const dueHistory=await rpc(office,'training_assignment_history',{p_assignment:a1});
  assert.deepEqual(dueHistory.filter(e=>e.action==='DUE_CHANGED').map(e=>[e.details.oldDueOn,e.details.newDueOn]),[['2026-11-10','2026-10-20'],['2026-10-20','2026-12-20']]);
  const zero1=await rpc(office,'training_assign',{p_person:personZero,p_course:course,p_version:v1.versionId,p_due:'2026-11-10',p_reason:'Synthetic remaining active v1 retirement proof',p_request:request()});
  const v2=await rpc(office,'training_create_draft',{p_course:course});
  await rpc(office,'training_edit_draft',{p_version:v2,p_revision:1,p_title:'Synthetic 20C v2',p_summary:'Separate immutable package',p_content:content('v2')});
  await rpc(office,'training_publish',{p_version:v2,p_revision:2});
  assert.equal((await rpc(staffA,'training_my_learning')).find(a=>a.id===a1).versionId,v1.versionId,'publication does not change assignment');
  assert.ok((await rpc(office,'training_assignment_history',{p_assignment:a1})).some(e=>e.action==='COURSE_PUBLISHED'&&e.details.note==='Publication did not change this assignment'));
  assert.equal((await rpc(staffA,'training_assignment_content',{p_assignment:a1})).assignment.viewedCount,1,'v1 progress unchanged');
  const staleArgs={p_person:personB,p_course:course,p_version:v1.versionId,p_due:'2026-11-10',p_reason:'Synthetic stale version assignment denial',p_request:request()};
  assert.ok((await office.rpc('training_assign',staleArgs)).error,'stale requested version rejected, never switched');
  const b2=await rpc(office,'training_assign',{...staleArgs,p_version:v2,p_request:request()});
  assert.equal((await rpc(staffB,'training_my_learning')).find(a=>a.id===b2).versionId,v2);
  await rpc(staffB,'training_mark_page',{p_assignment:b2,p_module:1,p_page:1});
  await rpc(staffB,'training_mark_page',{p_assignment:b2,p_module:1,p_page:2});
  assert.equal((await rpc(staffB,'training_my_learning')).find(a=>a.id===b2).viewedCount,2,'100% pages viewed');
  const noCompletion=await office.from('training_completions').select('*');
  assert.ok(noCompletion.error,'20C created no completion table');
  const supersedeArgs={p_assignment:a1,p_revision:3,p_version:v2,p_due:'2026-12-30',p_reason:'Synthetic explicit replacement of v1 assignment',p_request:request()};
  const concurrent=await Promise.all([office.rpc('training_supersede_assignment',supersedeArgs),office.rpc('training_supersede_assignment',{...supersedeArgs,p_request:request()})]);
  assert.equal(concurrent.filter(r=>!r.error).length,1,'one concurrent supersession wins');
  const a2=concurrent.find(r=>!r.error).data;
  const aHistory=await rpc(staffA,'training_my_learning');
  assert.equal(aHistory.find(a=>a.id===a1).state,'SUPERSEDED');
  assert.equal(aHistory.find(a=>a.id===a1).viewedCount,1,'old v1 history retained');
  assert.equal(aHistory.find(a=>a.id===a2).versionId,v2);
  assert.equal(aHistory.find(a=>a.id===a2).viewedCount,0,'no progress migration');
  assert.equal(aHistory.find(a=>a.id===a2).replacesAssignmentId,a1);
  assert.ok((await staffA.rpc('training_mark_page',{p_assignment:a1,p_module:1,p_page:2})).error,'superseded write blocked');
  await rpc(office,'training_retire',{p_version:v1.versionId,p_reason:'Synthetic retired historical version review proof'});
  const retired=(await rpc(staffZero,'training_my_learning')).find(a=>a.id===zero1);
  assert.equal(retired.state,'ACTIVE','retirement preserves active assignment');
  assert.equal(retired.retired,true);
  assert.ok((await staffZero.rpc('training_assignment_content',{p_assignment:zero1})).error,'retired content blocked');
  assert.ok((await staffZero.rpc('training_save_place',{p_assignment:zero1,p_module:1,p_page:1})).error,'retired progress blocked');
  assert.equal((await rpc(staffA,'training_assignment_content',{p_assignment:a2})).assignment.versionId,v2,'v2 remains accessible');
  await rpc(office,'training_cancel',{p_assignment:b2,p_revision:1,p_reason:'Synthetic cancellation preserves page history',p_request:request()});
  const cancelled=(await rpc(staffB,'training_my_learning')).find(a=>a.id===b2);
  assert.equal(cancelled.state,'CANCELLED');assert.equal(cancelled.viewedCount,2);
  assert.ok((await staffB.rpc('training_mark_page',{p_assignment:b2,p_module:1,p_page:1})).error,'cancelled writes blocked');
  const v3=await rpc(office,'training_create_draft',{p_course:course});
  await rpc(office,'training_publish',{p_version:v3,p_revision:1});
  const parallelArgs={p_person:personB,p_course:course,p_version:v3,p_due:'2027-01-15',p_reason:'Synthetic concurrent one active assignment proof'};
  const parallel=await Promise.all([office.rpc('training_assign',{...parallelArgs,p_request:request()}),office.rpc('training_assign',{...parallelArgs,p_request:request()})]);
  assert.equal(parallel.filter(r=>!r.error).length,1,'concurrent assignment has one winner');
  const b3=parallel.find(r=>!r.error).data;
  assert.equal((await rpc(staffB,'training_my_learning')).filter(a=>a.courseId===course&&a.state==='ACTIVE').length,1);
  assert.equal((await rpc(staffB,'training_my_learning')).find(a=>a.id===b3).versionId,v3);
  await rpc(office,'training_cancel',{p_assignment:b3,p_revision:1,p_reason:'Synthetic publish and assign race preparation',p_request:request()});
  const v4=await rpc(office,'training_create_draft',{p_course:course});
  const race=await Promise.all([office.rpc('training_publish',{p_version:v4,p_revision:1}),office.rpc('training_assign',{...parallelArgs,p_request:request()})]);
  assert.equal(race[0].error,null,'parallel publication succeeds');
  if (!race[1].error) assert.equal((await rpc(staffB,'training_my_learning')).find(a=>a.id===race[1].data).versionId,v3,'prior winner stays on requested v3');
  else assert.equal((await rpc(staffB,'training_my_learning')).filter(a=>a.courseId===course&&a.state==='ACTIVE').length,0,'publish winner causes stale assign denial');
  await rpc(admin,'training_assigner_revoke',{p_grant:grant,p_reason:'Synthetic 20C authority revocation proof'});
  assert.equal((await rpc(office,'training_assigner_access')).assigner,false);
  assert.ok((await office.rpc('training_cancel',{p_assignment:a2,p_revision:1,p_reason:'Revoked assigner cannot cancel',p_request:request()})).error);
  assert.ok((await rpc(admin,'training_assigner_grants_read')).some(g=>g.id===grant&&g.revokedAt));
 } finally {
  const grants=await rpc(admin,'training_assigner_grants_read');
  if(grants.some(g=>g.id===grant&&!g.revokedAt)) await rpc(admin,'training_assigner_revoke',{p_grant:grant,p_reason:'Synthetic 20C test cleanup revocation'});
 }
});
