import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createClient } from '@supabase/supabase-js';
import { signInWithTestSession } from './helpers/auth-session.mjs';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const creds={admin:'ADMIN',office:'OFFICE',officeB:'OFFICE_B',operations:'OPERATIONS',staffA:'STAFF_A',staffB:'STAFF_B'};
async function signed(name){const c=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const code=creds[name];const {error}=await signInWithTestSession(c,{email:process.env[`KSS_TEST_${code}_EMAIL`],password:process.env[`KSS_TEST_${code}_PASSWORD`]});assert.ifError(error);return c;}
async function rpc(c,name,args={}){const {data,error}=await c.rpc(name,args);assert.ifError(error,`${name}: ${error?.message}`);return data;}
const req=()=>crypto.randomUUID();
const questions=[{id:'q1',type:'SINGLE',prompt:'Synthetic: which option is designated?',options:[{id:'a',text:'Alpha'},{id:'b',text:'Beta'}],key:['a']},{id:'q2',type:'MULTIPLE',prompt:'Synthetic: select the designated pair',options:[{id:'a',text:'First'},{id:'b',text:'Second'},{id:'c',text:'Third'}],key:['a','c']}];
const boundaryQuestions=[...questions,...[3,4,5].map(i=>({id:`q${i}`,type:'SINGLE',prompt:`Synthetic boundary question ${i}`,options:[{id:'a',text:'Designated'},{id:'b',text:'Other'}],key:['a']}))];
const courseContent=[{title:'Synthetic module',pages:[{title:'Synthetic page',blocks:[{type:'paragraph',text:'Synthetic 20D assessment fixture only.'}]}]}];

test('TASK-20D exact-version attempts, deterministic result and negative access',{timeout:240000},async()=>{
 assert.ok(url?.includes('dnfhkmmnlbiabqypclqg'),'literal synthetic Dev target');
 const [admin,office,officeB,operations,staffA,staffB]=await Promise.all(Object.keys(creds).map(signed));
 const anon=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
 const officePerson='10000000-0000-4000-8000-000000000002',staffPerson='10000000-0000-4000-8000-000000000003';
 assert.equal((await rpc(admin,'training_assessment_access')).author,false,'Super Admin role alone cannot author');
 assert.ok((await admin.rpc('training_assessment_create',{p_course_version:crypto.randomUUID(),p_questions:questions})).error);
 assert.ok((await officeB.rpc('training_assessment_admin')).error);
 assert.ok((await operations.rpc('training_assessment_admin')).error);
 assert.ok((await anon.rpc('training_assessment_access')).error);
 assert.ok((await staffA.from('training_assessment_versions').select('*')).error,'direct table read denied');
 assert.ok((await staffA.from('training_submitted_answers').select('*')).error,'answer table read denied');
 const authorGrant=await rpc(admin,'training_assessment_grant',{p_person:officePerson,p_capability:'ASSESSMENT_AUTHOR',p_reason:'Synthetic 20D author capability proof'});
 const publisherGrant=await rpc(admin,'training_assessment_grant',{p_person:officePerson,p_capability:'ASSESSMENT_PUBLISHER',p_reason:'Synthetic 20D publisher capability proof'});
 const assignerGrant=await rpc(admin,'training_assigner_grant',{p_person:officePerson,p_from:new Date(Date.now()-60000).toISOString(),p_until:null,p_reason:'Synthetic 20D exact assignment proof'});
 try {
  const course=await rpc(office,'training_create_course',{p_title:`Synthetic 20D ${Date.now()}`,p_summary:'Synthetic assessment proof only',p_content:courseContent});
  const courseVersion=(await rpc(office,'training_admin',{p_course:course}))[0].versionId;
  await rpc(office,'training_publish',{p_version:courseVersion,p_revision:1});
  const assignment=await rpc(office,'training_assign',{p_person:staffPerson,p_course:course,p_version:courseVersion,p_due:'2026-12-10',p_reason:'Synthetic 20D assessment assignment',p_request:req()});
  const version=await rpc(office,'training_assessment_create',{p_course_version:courseVersion,p_questions:questions});
  await rpc(office,'training_assessment_publish',{p_version:version,p_revision:1});
  const before=await rpc(staffA,'training_assessment_staff',{p_assignment:assignment});
  assert.equal(before.history.length,0,'passive view does not start an attempt');
  assert.equal(JSON.stringify(before).includes('"key"'),false,'Staff projection has no scoring key');
  assert.equal(before.questions.length,2);
  assert.ok((await staffB.rpc('training_assessment_staff',{p_assignment:assignment})).error,'other Staff denied');
  assert.ok((await operations.rpc('training_assessment_staff',{p_assignment:assignment})).error,'Operations denied learner detail');
  assert.ok((await staffA.rpc('training_assessment_start',{p_assignment:crypto.randomUUID(),p_version:version,p_request:req()})).error,'wrong Assignment denied');
  assert.ok((await staffA.rpc('training_assessment_start',{p_assignment:assignment,p_version:crypto.randomUUID(),p_request:req()})).error,'wrong AssessmentVersion denied');
  const foreignCourse=await rpc(office,'training_create_course',{p_title:`Synthetic foreign 20D ${Date.now()}`,p_summary:'Synthetic wrong CourseVersion proof',p_content:courseContent});
  const foreignCourseVersion=(await rpc(office,'training_admin',{p_course:foreignCourse}))[0].versionId;
  await rpc(office,'training_publish',{p_version:foreignCourseVersion,p_revision:1});
  const foreignAssessmentVersion=await rpc(office,'training_assessment_create',{p_course_version:foreignCourseVersion,p_questions:boundaryQuestions});
  await rpc(office,'training_assessment_publish',{p_version:foreignAssessmentVersion,p_revision:1});
  assert.ok((await staffA.rpc('training_assessment_start',{p_assignment:assignment,p_version:foreignAssessmentVersion,p_request:req()})).error,'wrong CourseVersion chain denied');
  const foreignB=await rpc(office,'training_assign',{p_person:'10000000-0000-4000-8000-000000000004',p_course:foreignCourse,p_version:foreignCourseVersion,p_due:'2026-12-12',p_reason:'Synthetic 80 percent boundary proof',p_request:req()});
  const foreignBAttempt=await rpc(staffB,'training_assessment_start',{p_assignment:foreignB,p_version:foreignAssessmentVersion,p_request:req()});
  const eighty={q1:['a'],q2:['a','c'],q3:['a'],q4:['a'],q5:['b']};
  const boundaryResult=await rpc(staffB,'training_assessment_submit',{p_attempt:foreignBAttempt,p_revision:1,p_answers:eighty,p_request:req()});
  assert.equal(boundaryResult.scorePercent,80);assert.equal(boundaryResult.result,'PASSED','exact 80 percent passes');
  const foreignA=await rpc(office,'training_assign',{p_person:staffPerson,p_course:foreignCourse,p_version:foreignCourseVersion,p_due:'2026-12-12',p_reason:'Synthetic below-threshold grading proof',p_request:req()});
  const foreignAAttempt=await rpc(staffA,'training_assessment_start',{p_assignment:foreignA,p_version:foreignAssessmentVersion,p_request:req()});
  const sixty={...eighty,q4:['b']};
  const belowResult=await rpc(staffA,'training_assessment_submit',{p_attempt:foreignAAttempt,p_revision:1,p_answers:sixty,p_request:req()});
  assert.equal(belowResult.scorePercent,60);assert.equal(belowResult.result,'FAILED','60 percent fails');
  const startArgs={p_assignment:assignment,p_version:version,p_request:req()};
  const parallel=await Promise.all([staffA.rpc('training_assessment_start',startArgs),staffA.rpc('training_assessment_start',{...startArgs,p_request:req()})]);
  assert.equal(parallel.filter(r=>!r.error).length,2,'concurrent start resolves same open attempt');
  const attempt=parallel[0].data;assert.equal(parallel[1].data,attempt);
  assert.equal(await rpc(staffA,'training_assessment_start',startArgs),attempt,'identical start replay');
  assert.ok((await staffA.rpc('training_assessment_start',{...startArgs,p_version:crypto.randomUUID()})).error,'changed start replay denied');
  assert.ok((await staffB.rpc('training_assessment_save',{p_attempt:attempt,p_revision:1,p_answers:{q1:['a']},p_request:req()})).error,'wrong Person denied');
  assert.ok((await staffA.rpc('training_assessment_save',{p_attempt:attempt,p_revision:1,p_answers:{q1:['wrong']},p_request:req()})).error,'invalid option denied');
  assert.ok((await staffA.rpc('training_assessment_save',{p_attempt:attempt,p_revision:1,p_answers:{q99:['a']},p_request:req()})).error,'invalid question denied');
  const saveArgs={p_attempt:attempt,p_revision:1,p_answers:{q1:['b']},p_request:req()};
  assert.equal(await rpc(staffA,'training_assessment_save',saveArgs),2);
  assert.equal(await rpc(staffA,'training_assessment_save',saveArgs),2,'identical Save replay returns original revision');
  assert.ok((await staffA.rpc('training_assessment_save',{...saveArgs,p_answers:{q1:['a']}})).error,'changed Save replay denied');
  assert.equal((await rpc(staffA,'training_assessment_staff',{p_assignment:assignment})).openAttempt.draftAnswers.q1[0],'b','server draft resume');
  const wrong={q1:['b'],q2:['a','b']};
  assert.ok((await staffA.rpc('training_assessment_submit',{p_attempt:attempt,p_revision:1,p_answers:wrong,p_request:req()})).error,'stale revision denied');
  const submitArgs={p_attempt:attempt,p_revision:2,p_answers:wrong,p_request:req()};
  const result=await rpc(staffA,'training_assessment_submit',submitArgs);
  assert.equal(result.result,'FAILED');assert.equal(result.scorePercent,0);
  assert.equal((await rpc(staffA,'training_assessment_submit',submitArgs)).id,attempt,'identical submit replay');
  assert.ok((await staffA.rpc('training_assessment_submit',{...submitArgs,p_answers:{q1:['a'],q2:['a','c']}})).error,'changed payload replay denied');
  assert.ok((await staffA.rpc('training_assessment_start',{p_assignment:assignment,p_version:version,p_request:req()})).error,'30-minute retake enforced');
  assert.equal((await rpc(staffA,'training_assessment_staff',{p_assignment:assignment})).history.filter(a=>a.state==='SUBMITTED').length,1);
  assert.ok((await office.from('training_submitted_answers').update({answers:{}}).eq('attempt_id',attempt)).error,'direct immutable write denied');
  const noCompletion=await rpc(staffA,'training_completion_mine');
  assert.equal(noCompletion.filter(item=>item.assignmentId===assignment).length,0,'PASSED Attempt alone creates no Completion');
  assert.ok((await office.from('training_completions').select('*')).error,'Completion base table remains private');
  const v2=await rpc(office,'training_assessment_create',{p_course_version:courseVersion,p_questions:questions});
  await rpc(office,'training_assessment_publish',{p_version:v2,p_revision:1});
  let v2open=await rpc(staffA,'training_assessment_start',{p_assignment:assignment,p_version:v2,p_request:req()});
  const afterV2=await rpc(staffA,'training_assessment_staff',{p_assignment:assignment});
  assert.equal(afterV2.assessmentVersionId,v2,'new starts use v2');
  assert.equal(afterV2.history.find(a=>a.id===attempt).assessmentVersionId,version,'v1 result remains v1');
  await rpc(staffA,'training_assessment_abandon',{p_attempt:v2open,p_revision:1,p_request:req()});
  assert.equal((await rpc(staffA,'training_assessment_staff',{p_assignment:assignment})).attemptsRemaining,3,'abandon does not consume allowance');
  v2open=await rpc(staffA,'training_assessment_start',{p_assignment:assignment,p_version:v2,p_request:req()});
  assert.ok(v2open,'new Attempt after abandonment');
  const v3=await rpc(office,'training_assessment_create',{p_course_version:courseVersion,p_questions:questions});
  await rpc(office,'training_assessment_publish',{p_version:v3,p_revision:1});
  assert.equal((await rpc(staffA,'training_assessment_staff',{p_assignment:assignment})).openAttempt.assessmentVersionId,v2,'publication preserves open v2 Attempt');
  const correct={q1:['a'],q2:['c','a']};
  const same=await Promise.all([staffA.rpc('training_assessment_submit',{p_attempt:v2open,p_revision:1,p_answers:correct,p_request:req()}),staffA.rpc('training_assessment_submit',{p_attempt:v2open,p_revision:1,p_answers:correct,p_request:req()})]);
  assert.equal(same.filter(r=>!r.error).length,2,'concurrent identical Submit returns one result');
  assert.equal(same[0].data.id,same[1].data.id);
  assert.equal(same[0].data.result,'PASSED');assert.equal(same[0].data.scorePercent,100);
  assert.ok((await staffA.rpc('training_assessment_submit',{p_attempt:v2open,p_revision:1,p_answers:wrong,p_request:req()})).error,'changed submitted payload denied');
  const mixed=await rpc(staffA,'training_assessment_staff',{p_assignment:assignment});
  assert.equal(mixed.assessmentVersionId,v3,'v3 is current for new starts');
  assert.equal(mixed.history.filter(a=>a.state==='SUBMITTED').length,2,'v1 and v2 submissions remain separate');
  assert.equal(mixed.attemptsRemaining,3,'v3 has independent allowance');
  const v3open=await rpc(staffA,'training_assessment_start',{p_assignment:assignment,p_version:v3,p_request:req()});
  await rpc(office,'training_cancel',{p_assignment:assignment,p_revision:1,p_reason:'Synthetic 20D source-state block proof',p_request:req()});
  assert.ok((await staffA.rpc('training_assessment_save',{p_attempt:v3open,p_revision:1,p_answers:{q1:['a']},p_request:req()})).error,'cancelled source blocks draft writes');
  assert.ok((await staffA.rpc('training_assessment_submit',{p_attempt:v3open,p_revision:1,p_answers:correct,p_request:req()})).error,'cancelled source blocks Submit');
  assert.equal((await rpc(staffA,'training_assessment_staff',{p_assignment:assignment})).history.find(a=>a.id===v3open).state,'IN_PROGRESS','blocked open Attempt remains historical');
  await rpc(admin,'training_assessment_revoke',{p_grant:authorGrant,p_reason:'Synthetic 20D author proof ended'});
  assert.ok((await office.rpc('training_assessment_create',{p_course_version:courseVersion,p_questions:questions})).error,'revoked author denied');
  await rpc(admin,'training_assessment_revoke',{p_grant:publisherGrant,p_reason:'Synthetic 20D publisher proof ended'});
  assert.ok((await office.rpc('training_assessment_admin_history',{p_assignment:assignment})).error,'assigner grant alone cannot inspect attempt history');
 } finally {
  const grants=await rpc(admin,'training_assessment_grants_read');
  for(const id of [authorGrant,publisherGrant]) if(grants.some(g=>g.id===id&&!g.revokedAt)) await rpc(admin,'training_assessment_revoke',{p_grant:id,p_reason:'Synthetic 20D temporary grant cleanup'});
  const assigners=await rpc(admin,'training_assigner_grants_read');
  if(assigners.some(g=>g.id===assignerGrant&&!g.revokedAt)) await rpc(admin,'training_assigner_revoke',{p_grant:assignerGrant,p_reason:'Synthetic 20D temporary grant cleanup'});
 }
});
