"use client";

import { useCallback,useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import styles from "./attendance.module.css";

type Row={allocation_id:string;person_name:string;status:string;service_date:string;report_at:string;shift_starts_at:string;shift_ends_at:string;area_label:string;role_name:string;site_name:string;reporting_point:string|null;attendance:{revision:number;state:string;check_in_at:string|null;check_out_at:string|null;no_show_recorded:boolean;review_required:boolean;events:{id:string;revision:number;type:string;actual_at:string|null;effective_actual_at:string|null;recorded_at:string;actor_name:string;reason:string|null;correction_code:string|null;corrects_event_id:string|null}[]}};
const london=(v:string|null)=>v?new Date(v).toLocaleString("en-GB",{timeZone:"Europe/London",weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"Not recorded";
const londonInput=(v:string)=>{const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(v));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;};
function londonInstant(value:string){const m=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value);if(!m)return null;const wall=Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(m[4]),Number(m[5]));const matches=[0,60].map(offset=>new Date(wall-offset*60000)).filter(d=>londonInput(d.toISOString())===value);return matches.length===1?matches[0].toISOString():null;}
export function EventAttendanceClient({eventId}:{eventId:string}){
 const [items,setItems]=useState<Row[]>([]);const [counts,setCounts]=useState<Record<string,number>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState("");const [notes,setNotes]=useState<Record<string,string>>({});const [correctionDrafts,setCorrectionDrafts]=useState<Record<string,{eventId:string;local:string}>>({});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/events/${eventId}/attendance`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error??"Attendance unavailable");setItems(d.attendance?.items??[]);setCounts(d.attendance?.counts??{});setError("");}catch(e){setError(e instanceof Error?e.message:"Attendance unavailable");}finally{setLoading(false);}},[eventId]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);
 async function submit(row:Row,action:string,extra:Record<string,unknown>={}){setBusy(row.allocation_id);setError("");setNotice("");const reason=notes[row.allocation_id]??"";const correction=action.startsWith("RESOLVE_")||action==="CORRECT_TIMESTAMP";const storageKey=`kss-attendance-manager-retry:${row.allocation_id}:${action}:${String(extra.targetEventId??"")}`;
  let payload:Record<string,unknown>;try{const saved=localStorage.getItem(storageKey);const parsed=saved?JSON.parse(saved):null;if(parsed&&parsed.action===action&&parsed.reason===reason)payload=parsed.payload;else throw new Error("new");}catch{payload=correction?{allocationId:row.allocation_id,targetEventId:extra.targetEventId,correction,actualAt:extra.actualAt,reason,expectedRevision:row.attendance.revision,idempotencyKey:crypto.randomUUID()}:{allocationId:row.allocation_id,action,actualAt:["CHECK_IN","CHECK_OUT"].includes(action)?new Date().toISOString():null,reasonCode:action==="NO_SHOW_RECORDED"?"NO_SHOW":action==="EXCUSED_ABSENCE_RECORDED"?"EXCUSED":action==="CHECK_IN_NOT_POSSIBLE"?"CHECK_IN_NOT_POSSIBLE":action==="REVIEW_REQUIRED"?"OTHER":null,reason,expectedRevision:row.attendance.revision,idempotencyKey:crypto.randomUUID()};localStorage.setItem(storageKey,JSON.stringify({action,reason,payload}));}
  try{const r=await fetch(`/api/events/${eventId}/attendance`,{method:correction?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"Action was not recorded. Refresh and resolve the current state.");localStorage.removeItem(storageKey);if(action==="CORRECT_TIMESTAMP")setCorrectionDrafts(current=>{const next={...current};delete next[row.allocation_id];return next;});setNotice("Attendance fact recorded with your identity.");await load();}catch(e){setError(e instanceof Error?e.message:"Attendance was not recorded.");}finally{setBusy("");}}
 return <section className={styles.wrap}><header className={styles.heading}><h1>Event attendance</h1><p>Attendance records factual events for this Event’s allocations. Scheduled and actual times remain separate; no punctuality or worked-time judgement is calculated.</p></header>
  <div className={styles.card}><strong>Expected {counts.expected??0} · Checked in {counts.checked_in??0} · Checked out {counts.checked_out??0} · Exceptions {counts.exceptions??0} · Review pending {counts.review_pending??0}</strong></div>
  {notice&&<p role="status" className={styles.success}>{notice}</p>}{error&&<p role="alert" className={styles.error}>{error} <Button variant="outline" onClick={()=>void load()}>Refresh</Button></p>}
  {loading?<p role="status">Loading operational attendance…</p>:items.length===0?<p className={styles.empty}>No allocations to show.</p>:items.map(row=>{const unresolvedNoShow=row.attendance.events.find(e=>e.type==="NO_SHOW_RECORDED"&&!row.attendance.events.some(c=>c.correction_code==="RESOLVE_NO_SHOW_FOR_CHECK_IN"&&c.corrects_event_id===e.id));const unresolvedReview=row.attendance.events.find(e=>e.type==="REVIEW_REQUIRED"&&!row.attendance.events.some(c=>c.correction_code==="RESOLVE_CANCELLED_ALLOCATION_REVIEW"&&c.corrects_event_id===e.id));const active=row.status!=="CANCELLED";return <article className={styles.card} key={row.allocation_id}>
   <div className={styles.row}><div><span className={styles.state}>{row.attendance.state.replaceAll("_"," ")}</span><h2>{row.person_name}</h2><p>{row.role_name}{row.area_label?` · ${row.area_label}`:""} · {row.status}</p></div><div className={styles.muted}>Report {london(row.report_at)}<br/>Shift {london(row.shift_starts_at)} – {london(row.shift_ends_at)}</div></div>
   <p>Check-in {london(row.attendance.check_in_at)} · Check-out {london(row.attendance.check_out_at)}</p>
   <label className={styles.muted}>Operational reason / resolution note · avoid sensitive personal details<input maxLength={300} value={notes[row.allocation_id]??""} onChange={e=>setNotes({...notes,[row.allocation_id]:e.target.value})} /></label>
   <div className={styles.actions}>
    {!row.attendance.check_in_at&&active&&<><Button disabled={Boolean(busy)} onClick={()=>void submit(row,"CHECK_IN")}>Record observed check-in</Button>{!row.attendance.no_show_recorded&&<Button variant="outline" disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()} onClick={()=>void submit(row,"NO_SHOW_RECORDED")}>Record no-show</Button>}<Button variant="outline" disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()} onClick={()=>void submit(row,"EXCUSED_ABSENCE_RECORDED")}>Record excused absence</Button><Button variant="outline" disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()} onClick={()=>void submit(row,"CHECK_IN_NOT_POSSIBLE")}>Check-in not possible</Button><Button variant="outline" disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()} onClick={()=>void submit(row,"REVIEW_REQUIRED")}>Mark for review</Button></>}
    {row.attendance.check_in_at&&!row.attendance.check_out_at&&<Button disabled={Boolean(busy)} onClick={()=>void submit(row,"CHECK_OUT")}>Record observed check-out</Button>}
    {unresolvedNoShow&&<Button disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()} onClick={()=>void submit(row,"RESOLVE_NO_SHOW_FOR_CHECK_IN",{targetEventId:unresolvedNoShow.id,actualAt:new Date().toISOString()})}>Resolve no-show and record observed check-in</Button>}
    {unresolvedReview&&row.status==="CANCELLED"&&<Button variant="outline" disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()} onClick={()=>void submit(row,"RESOLVE_CANCELLED_ALLOCATION_REVIEW",{targetEventId:unresolvedReview.id})}>Resolve cancellation review</Button>}
   </div>
    {row.attendance.events.length>0&&<div className={styles.events}><h3>Factual history</h3>{row.attendance.events.map(e=><div className={styles.event} key={e.id}><span><strong>{e.type.replaceAll("_"," ")}</strong>{e.reason?` · ${e.reason}`:""}</span><span className={styles.muted}>{london(e.effective_actual_at??e.recorded_at)} · {e.actor_name}</span>{["CHECK_IN","CHECK_OUT"].includes(e.type)&&!row.attendance.events.some(c=>c.correction_code==="CORRECT_TIMESTAMP"&&c.corrects_event_id===e.id)&&<div><Button variant="outline" size="sm" disabled={Boolean(busy)} onClick={()=>setCorrectionDrafts({...correctionDrafts,[row.allocation_id]:{eventId:e.id,local:londonInput(e.effective_actual_at??e.actual_at??e.recorded_at)}})}>Correct recorded time</Button>{correctionDrafts[row.allocation_id]?.eventId===e.id&&<div className={styles.actions}><label>Correct actual time · Europe/London<input type="datetime-local" value={correctionDrafts[row.allocation_id].local} onChange={event=>setCorrectionDrafts({...correctionDrafts,[row.allocation_id]:{eventId:e.id,local:event.target.value}})}/></label><Button disabled={Boolean(busy)||!(notes[row.allocation_id]??"").trim()||!londonInstant(correctionDrafts[row.allocation_id].local)} onClick={()=>{const actualAt=londonInstant(correctionDrafts[row.allocation_id].local);if(actualAt)void submit(row,"CORRECT_TIMESTAMP",{targetEventId:e.id,actualAt});}}>Save correction</Button></div>}</div>}</div>)}</div>}
  </article>})}
 </section>;
}
