"use client";
import {useEffect,useState} from "react";
type Row={personId:string;displayName:string;hasOperationsRole:boolean;grant:null|{id:string;effectiveFrom:string;effectiveUntil:string;grantedBy:string;grantReason:string;revokedAt:string|null;revokedBy:string|null;revocationReason:string|null;active:boolean}};
const londonToday=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`};
export function IncidentReviewerAdmin(){
 const [rows,setRows]=useState<Row[]>([]),[personId,setPersonId]=useState(""),[until,setUntil]=useState(""),[reason,setReason]=useState(""),[revokeReason,setRevokeReason]=useState(""),[revokingId,setRevokingId]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 useEffect(()=>{let alive=true;fetch("/api/access/incident-reviewers",{cache:"no-store"}).then(async r=>({r,j:await r.json()})).then(({r,j})=>{if(!alive)return;if(!r.ok)setError(j.error??"Reviewer grants unavailable");else setRows(j.reviewers??[])}).catch(()=>{if(alive)setError("Reviewer grants unavailable")});return()=>{alive=false}},[]);
 const load=async()=>{const r=await fetch("/api/access/incident-reviewers",{cache:"no-store"});const j=await r.json();if(!r.ok){setError(j.error??"Reviewer grants unavailable");return}setRows(j.reviewers??[])};
 const candidates=rows.filter(r=>r.hasOperationsRole&&(!r.grant||r.grant.revokedAt));
 async function grant(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setSuccess("");const r=await fetch("/api/access/incident-reviewers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({personId,lastActiveDate:until,reason})});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error??"Grant not recorded");return}setReason("");setSuccess("Incident Reviewer grant recorded.");await load()}
 async function revoke(e:React.FormEvent,row:Row){e.preventDefault();if(!row.grant)return;setBusy(true);setError("");const r=await fetch(`/api/access/incident-reviewers/${row.grant.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:revokeReason})});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error??"Grant not revoked");return}setRevokingId(null);setRevokeReason("");setSuccess("Incident Reviewer grant revoked.");await load()}
 return <div className="incident-workspace"><section className="incident-card"><h2>Grant access</h2><p>Grant only people with an active Operations role. Access ends at the end of the selected UK date. A reason is recorded in the grant history.</p><form className="incident-action-form" onSubmit={grant}><label>Operations reviewer<select required value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Choose a person</option>{candidates.map(r=><option key={r.personId} value={r.personId}>{r.displayName}</option>)}</select></label><label>Last active date<input required type="date" value={until} min={londonToday()} onChange={e=>setUntil(e.target.value)}/></label><label>Reason<textarea required minLength={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="incident-primary" disabled={busy||!personId||!until||reason.trim().length<3}>{busy?"Saving…":"Grant Incident Reviewer access"}</button></form></section><section className="incident-card"><h2>Reviewer grant history</h2>{rows.length===0?<p className="incident-empty">No current or recorded reviewers.</p>:<ul className="incident-list">{rows.map(r=><li key={r.personId}><div className="incident-grant-row"><strong>{r.displayName}</strong><span>{r.hasOperationsRole?"Active Operations role":"Operations role inactive"} · {r.grant?.active?"Grant active":r.grant?.revokedAt?"Grant revoked":"No grant"}</span>{r.grant&&<small>Until {new Date(r.grant.effectiveUntil).toLocaleDateString("en-GB",{timeZone:"Europe/London"})} · Granted by {r.grant.grantedBy} · {r.grant.grantReason}{r.grant.revocationReason?` · Revocation: ${r.grant.revocationReason}`:""}</small>}{r.grant&&!r.grant.revokedAt&&(revokingId===r.grant.id?<form className="incident-action-form" onSubmit={e=>void revoke(e,r)}><label>Reason for revoking this grant<textarea required minLength={3} maxLength={300} value={revokeReason} onChange={e=>setRevokeReason(e.target.value)}/></label><button className="incident-primary" disabled={busy||revokeReason.trim().length<3}>{busy?"Saving…":"Confirm revocation"}</button><button type="button" className="incident-secondary" disabled={busy} onClick={()=>{setRevokingId(null);setRevokeReason("")}}>Cancel</button></form>:<button className="incident-secondary" disabled={busy} onClick={()=>{setRevokingId(r.grant!.id);setRevokeReason("")}}>Revoke grant</button>)}</div></li>)}</ul>}</section>{error&&<p className="incident-error" role="alert">{error}</p>}{success&&<p className="incident-success" role="status">{success}</p>}</div>
}
