"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";

type Item = { id:string; status:string; revision:number; createdAt:string; occurredAt:string; category:string; contextLabel:string; reporterName?:string; hasCorrection?:boolean };
type Choice = {kind:string;id:string;label:string};
const categories = [["SAFETY_HAZARD","Safety hazard"],["INJURY_OR_ILLNESS_REPORTED","Injury or illness reported"],["SECURITY_OCCURRENCE","Security occurrence"],["PROPERTY_DAMAGE_OR_LOSS","Property damage or loss"],["SERVICE_DISRUPTION","Service disruption"],["OTHER_OPERATIONAL","Other operational issue"]];
const statusLabel = (s:string) => s.replaceAll("_"," ").toLowerCase().replace(/^./,x=>x.toUpperCase());
function londonParts(date:string,time:string) {
  const [y,m,d]=date.split("-").map(Number),[hh,mm]=time.split(":").map(Number); const target=Date.UTC(y,m-1,d,hh,mm);
  const fmt=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"});
  const matches:string[]=[];
  for(let delta=-120;delta<=120;delta+=15){const t=target+delta*60000;const parts=Object.fromEntries(fmt.formatToParts(t).map(p=>[p.type,p.value]));if(`${parts.year}-${parts.month}-${parts.day}`===date&&`${parts.hour}:${parts.minute}`===time)matches.push(new Date(t).toISOString());}
  return matches;
}
function todayLondon(){const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;}

export function IncidentsWorkspace({staff,reviewer}:{staff:boolean;reviewer:boolean}) {
 const [items,setItems]=useState<Item[]>([]),[choices,setChoices]=useState<Choice[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const pendingSubmission=useRef<{signature:string;key:string}|null>(null);
 const [date,setDate]=useState(todayLondon()),[time,setTime]=useState("12:00"),[selected,setSelected]=useState(""),[category,setCategory]=useState("SAFETY_HAZARD"),[narrative,setNarrative]=useState(""),[relationship,setRelationship]=useState(""),[descriptor,setDescriptor]=useState(""),[ambiguous,setAmbiguous]=useState("");
 async function load(){setError("");const r=await fetch("/api/incidents",{cache:"no-store"});const j=await r.json();if(!r.ok){setError(j.error??"Incident reports unavailable");return;}setItems(j.result?.items??[]);}
 useEffect(()=>{let alive=true;fetch("/api/incidents",{cache:"no-store"}).then(async r=>({r,j:await r.json()})).then(({r,j})=>{if(!alive)return;if(!r.ok)setError(j.error??"Incident reports unavailable");else setItems(j.result?.items??[])}).catch(()=>{if(alive)setError("Incident reports unavailable")});if(staff)fetch("/api/incidents?mode=context",{cache:"no-store"}).then(r=>r.json()).then(j=>{if(alive)setChoices(j.choices??[])}).catch(()=>{if(alive)setChoices([])});return()=>{alive=false}},[staff]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setSuccess("");const candidates=londonParts(date,time);if(candidates.length===0){setError("That time does not exist in UK local time. Choose another time.");return;}let occurredAt=candidates[0];if(candidates.length>1){if(!ambiguous){setError("This time occurs twice when the UK clocks change. Choose the earlier or later occurrence.");return;}occurredAt=candidates[ambiguous==="later"?candidates.length-1:0];}if(Date.parse(occurredAt)>Date.now()){setError("Choose a time that has already occurred.");return;}
   setBusy(true);const context:Record<string,string>={};const choice=choices.find(x=>`${x.kind}:${x.id}`===selected);if(choice){if(choice.kind==="SITE")context.siteId=choice.id;if(choice.kind==="EVENT")context.eventId=choice.id;if(choice.kind==="SITE_SERVICE")context.siteServiceId=choice.id;if(choice.kind==="EVENT_ALLOCATION")context.eventAllocationId=choice.id;if(choice.kind==="SITE_SHIFT_ALLOCATION")context.siteShiftAllocationId=choice.id;}
   const base={occurredAt,category,narrative:narrative.trim(),context,externalParties:relationship?[{relationship,descriptor}]:[]};const signature=JSON.stringify(base);if(!pendingSubmission.current||pendingSubmission.current.signature!==signature)pendingSubmission.current={signature,key:crypto.randomUUID()};const idempotencyKey=pendingSubmission.current.key;
   try{const r=await fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idempotencyKey,...base})});const j=await r.json();if(!r.ok){const check=await fetch(`/api/incidents?submissionKey=${encodeURIComponent(idempotencyKey)}`,{cache:"no-store"}).then(x=>x.json()).catch(()=>null);setBusy(false);if(check?.result?.found){pendingSubmission.current=null;setNarrative("");setSuccess("KSS confirmed your report. Its current status is OPEN.");await load();return;}setError(j.error??"Report not confirmed. Retry this submission; the same request key will be reused.");return;}pendingSubmission.current=null;setNarrative("");setDescriptor("");setRelationship("");setAmbiguous("");setSuccess("Your report has been submitted and its current status is OPEN.");await load();}catch{const check=await fetch(`/api/incidents?submissionKey=${encodeURIComponent(idempotencyKey)}`,{cache:"no-store"}).then(x=>x.json()).catch(()=>null);setBusy(false);if(check?.result?.found){pendingSubmission.current=null;setNarrative("");setSuccess("KSS confirmed your report. Its current status is OPEN.");await load();return;}setError("KSS has not confirmed receipt. Retry this unchanged submission; the same request key will be reused.");}}
 return <div className="incident-workspace">{staff&&<section className="incident-card incident-report-card"><div className="incident-emergency"><strong>Emergency guidance</strong><p>KSS Enterprise incident reporting is not an emergency service. If there is an immediate risk to life or safety, follow the site’s emergency procedure and contact the appropriate emergency service before completing this report.</p></div>
 <form className="incident-form" onSubmit={submit}><div className="incident-section-title"><span>01</span><div><h2>What happened?</h2><p>Record the operational facts you know. Do not include medical detail, allegations or contact information.</p></div></div>
 <div className="incident-form-grid"><label>When did it happen?<input required type="date" value={date} max={todayLondon()} onChange={e=>{setDate(e.target.value);setAmbiguous("")}} /></label><label>Approximate UK local time<input required type="time" value={time} onChange={e=>{setTime(e.target.value);setAmbiguous("")}} /></label></div>
 {ambiguous!==""&&<label>UK clock change<select value={ambiguous} onChange={e=>setAmbiguous(e.target.value)}><option value="">Choose one</option><option value="earlier">Earlier occurrence</option><option value="later">Later occurrence</option></select></label>}
 <label>Incident category<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Context (optional)<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">No linked context / not known</option>{choices.map(x=><option key={`${x.kind}-${x.id}`} value={`${x.kind}:${x.id}`}>{x.label}</option>)}</select><small>Only choose context you know is correct. You can report without it.</small></label>
 <label>Factual description<textarea required minLength={10} maxLength={6000} rows={5} value={narrative} onChange={e=>setNarrative(e.target.value)} placeholder="Describe what happened, where, and any immediate operational impact." /><small>{narrative.length}/6000 · Avoid names, addresses, contact details, identity information, medical details and speculation.</small></label>
 <fieldset className="incident-party"><legend>External person (optional)</legend><p>Use a relationship and a short neutral descriptor only. Do not include names, addresses, dates of birth or identifying/contact details.</p><label>Relationship<select value={relationship} onChange={e=>setRelationship(e.target.value)}><option value="">None</option><option value="MEMBER_OF_PUBLIC">Member of public</option><option value="CLIENT_REPRESENTATIVE">Client representative</option><option value="CONTRACTOR">Contractor</option><option value="WITNESS">Witness</option><option value="OTHER">Other</option></select></label>{relationship&&<label>Short neutral descriptor<input required maxLength={120} value={descriptor} onChange={e=>setDescriptor(e.target.value)} placeholder="For example: male wearing blue jacket" /></label>}</fieldset>
 {error&&<p className="incident-error" role="alert">{error}</p>}{success&&<p className="incident-success" role="status">{success}</p>}
 <button className="incident-primary" disabled={busy}>{busy?"Submitting report…":"Submit incident report"}</button><p className="incident-submit-note">Online submission only. KSS must confirm receipt before it is treated as submitted.</p></form></section>}
 {reviewer&&<section className="incident-card"><div className="incident-section-title"><span>01</span><div><h2>Operational review queue</h2><p>Reports across the organisation, including those without linked context. Open a report to see its exact version and reviewer history.</p></div></div>{error&&!staff&&<p className="incident-error" role="alert">{error}</p>}{items.length===0?<p className="incident-empty">No incident reports are available in this queue.</p>:<ul className="incident-list">{items.map(x=><li key={x.id}><Link href={`/incidents/${x.id}`}><span className="incident-list-top"><strong>{categories.find(([v])=>v===x.category)?.[1]??x.category}</strong><span className="incident-status">{statusLabel(x.status)}</span></span><span>{x.contextLabel}</span><small>Occurred {new Date(x.occurredAt).toLocaleString("en-GB",{timeZone:"Europe/London"})} · Reported by {x.reporterName??"Reporter unavailable"}</small><span className="incident-list-action">Open report →</span></Link></li>)}</ul>}</section>}
 {staff&&<section className="incident-card"><div className="incident-section-title"><span>02</span><div><h2>Your reports</h2><p>See your submissions, corrections and current status.</p></div></div>{items.length===0?<p className="incident-empty">Your submitted reports will appear here.</p>:<ul className="incident-list">{items.map(x=><li key={x.id}><Link href={`/incidents/${x.id}`}><strong>{categories.find(([v])=>v===x.category)?.[1]??x.category}</strong><span>{statusLabel(x.status)}{x.hasCorrection?" · Correction recorded":""}</span><small>{x.contextLabel} · {new Date(x.occurredAt).toLocaleString("en-GB",{timeZone:"Europe/London"})}</small></Link></li>)}</ul>}</section>}</div>;
}
