"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Detail={id:string;reporterName:string|null;status:string;revision:number;reportVersion:number;reports:{version:number;occurredAt:string;category:string;narrative:string;contextLabel:string;context:Record<string,string|null>;correctionReason:string|null;recordedAt:string;externalParties:{relationship:string;descriptor:string}[]}[];events:{kind:string;status:string;actionCode:string|null;reason:string|null;actorName:string|null;recordedAt:string}[];viewerCanReview:boolean;viewerOwnReport:boolean};
const actions=[{code:"AREA_MADE_SAFE",label:"Area made safe"},{code:"DUTY_MANAGER_CONTACTED",label:"Duty manager contacted"},{code:"SERVICE_CONTINUED_WITH_CONTROL",label:"Service continued with control"},{code:"SERVICE_PAUSED",label:"Service paused"},{code:"EXTERNAL_PROCESS_REFERRED",label:"External process referred"},{code:"FOLLOW_UP_REQUIRED",label:"Follow-up required"},{code:"OTHER_OPERATIONAL_ACTION",label:"Other operational action"}];
const readable=(s:string)=>s.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase());
export function IncidentDetail({id,staff,reviewer}:{id:string;staff:boolean;reviewer:boolean}){
 const [item,setItem]=useState<Detail|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[action,setAction]=useState("ACKNOWLEDGE"),[code,setCode]=useState(actions[0].code),[reason,setReason]=useState("");
 async function load():Promise<boolean>{try{const r=await fetch(`/api/incidents/${id}`,{cache:"no-store"});const j=await r.json();if(!r.ok){setError("Incident unavailable");return false;}setItem(j.incident);return true;}catch{setError("Incident unavailable");return false;}}
 useEffect(()=>{let alive=true;fetch(`/api/incidents/${id}`,{cache:"no-store"}).then(async r=>({r,j:await r.json()})).then(({r,j})=>{if(!alive)return;if(!r.ok)setError("Incident unavailable");else setItem(j.incident)}).catch(()=>{if(alive)setError("Incident unavailable")});return()=>{alive=false}},[id]);
 async function mutate(path:string,body:Record<string,unknown>){setBusy(true);setError("");try{const r=await fetch(path,{method:path.includes("actions")?"POST":"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error??"Action not recorded. Refresh and try again.");return false;}if(!await load()){setError("The action was accepted, but the current Incident could not be refreshed. Refresh before acting again.");return false;}setReason("");return true;}catch{setError("Action not confirmed. Refresh the Incident before retrying.");return false;}finally{setBusy(false);}}
 if(error&&!item)return <p className="incident-error" role="alert">{error}</p>;if(!item)return <p>Loading incident…</p>;
 const current=item.reports.find(x=>x.version===item.reportVersion)!;
 const allowedActions=item.status==="OPEN"?["ACKNOWLEDGE"]:item.status==="ACTION_RECORDED"?["ACTION_RECORDED","CLOSE"]:["ACTION_RECORDED"];
 const selectedAction=allowedActions.includes(action)?action:allowedActions[0];
 return <div className="incident-detail"><Link className="incident-back" href="/incidents">← {staff?"Your reports":"Incident queue"}</Link><header className="incident-detail-head"><p className="incident-eyebrow">Incident · {item.id.slice(0,8)}</p><h1>{readable(current.category)}</h1><p><strong>{readable(item.status)}</strong> · Report version {item.reportVersion}{reviewer&&item.reporterName?` · Submitted by ${item.reporterName}`:""}</p></header>{error&&<p className="incident-error" role="alert">{error}</p>}
 <section className="incident-card"><h2>Submitted report</h2><p className="incident-meta">Occurred {new Date(current.occurredAt).toLocaleString("en-GB",{timeZone:"Europe/London"})} · {current.contextLabel}</p><p className="incident-narrative">{current.narrative}</p>{current.externalParties.length>0&&<div><strong>External person(s)</strong>{current.externalParties.map((p,i)=><p key={i}>{readable(p.relationship)} — {p.descriptor}</p>)}</div>}</section>
 {item.reports.length>1&&<section className="incident-card"><h2>Corrections</h2>{item.reports.slice(0,-1).map(r=><article className="incident-version" key={r.version}><h3>Earlier version {r.version}{r.version===1?" · Original":""}</h3><p className="incident-meta">{new Date(r.recordedAt).toLocaleString("en-GB",{timeZone:"Europe/London"})} · {r.contextLabel}</p><p className="incident-narrative">{r.narrative}</p>{r.correctionReason&&<p><strong>Correction reason:</strong> {r.correctionReason}</p>}</article>)}</section>}
 {staff&&item.viewerOwnReport&&<section className="incident-card"><h2>Status history</h2><ol className="incident-timeline">{item.events.map((e,i)=><li key={`${e.kind}-${i}`}><strong>{e.kind==="CORRECTED"?"Correction recorded":readable(e.status)}</strong><span>{new Date(e.recordedAt).toLocaleString("en-GB",{timeZone:"Europe/London"})}</span></li>)}</ol></section>}
 {reviewer&&<section className="incident-card"><h2>Operational follow-up</h2><p>Actions and reviewer notes are visible to authorised Operations reviewers and Super Admin only.</p><ol className="incident-timeline">{item.events.filter(e=>e.kind!=="REPORTED"&&e.kind!=="CORRECTED").map((e,i)=><li key={`${e.kind}-${i}`}><strong>{e.actionCode?actions.find(a=>a.code===e.actionCode)?.label:readable(e.status)}</strong>{e.reason&&<p>{e.reason}</p>}<span>{e.actorName} · {new Date(e.recordedAt).toLocaleString("en-GB",{timeZone:"Europe/London"})}</span></li>)}</ol>
 {item.status!=="CLOSED"&&<form className="incident-action-form" onSubmit={e=>{e.preventDefault();void mutate(`/api/incidents/${id}/actions`,{expectedRevision:item.revision,idempotencyKey:crypto.randomUUID(),action:selectedAction,...(selectedAction==="ACTION_RECORDED"?{actionCode:code}:{}),...(selectedAction==="REOPEN"?{reason:reason.trim()}:{})});}}><label>Next action<select value={selectedAction} onChange={e=>setAction(e.target.value)}>{item.status==="OPEN"&&<option value="ACKNOWLEDGE">Acknowledge report</option>}{["ACKNOWLEDGED","ACTION_RECORDED","REOPENED"].includes(item.status)&&<option value="ACTION_RECORDED">Record operational action</option>}{item.status==="ACTION_RECORDED"&&<option value="CLOSE">Close incident</option>}</select></label>{selectedAction==="ACTION_RECORDED"&&<label>Operational action<select value={code} onChange={e=>setCode(e.target.value)}>{actions.map(a=><option value={a.code} key={a.code}>{a.label}</option>)}</select></label>}{selectedAction==="ACTION_RECORDED"&&<button className="incident-primary" disabled={busy}>Record action</button>}{selectedAction==="ACKNOWLEDGE"&&<button className="incident-primary" disabled={busy}>Acknowledge</button>}{selectedAction==="CLOSE"&&<button className="incident-primary" disabled={busy}>Close incident</button>}</form>}
 {item.status==="CLOSED"&&<form className="incident-action-form" onSubmit={e=>{e.preventDefault();void mutate(`/api/incidents/${id}/actions`,{expectedRevision:item.revision,idempotencyKey:crypto.randomUUID(),action:"REOPEN",reason:reason.trim()});}}><label>Reason for reopening<textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="incident-primary" disabled={busy||reason.trim().length<3}>Reopen incident</button></form>}
 {error&&<p className="incident-error" role="alert">{error}</p>}</section>}
 {staff&&item.viewerOwnReport&&<CorrectionForm item={item} id={id} onSaved={load} onError={setError} />}
 </div>;
}
function CorrectionForm({item,id,onSaved,onError}:{item:Detail;id:string;onSaved:()=>Promise<boolean>;onError:(x:string)=>void}){
 const current=item.reports.find(x=>x.version===item.reportVersion)!;const [open,setOpen]=useState(false),[reason,setReason]=useState(""),[busy,setBusy]=useState(false),[text,setText]=useState(current.narrative);
 return <section className="incident-card"><h2>Correction</h2><p>Corrections add a new version. Earlier submitted text remains in the history.</p>{!open?<button className="incident-secondary" onClick={()=>setOpen(true)}>Record a correction</button>:<form className="incident-action-form" onSubmit={async e=>{e.preventDefault();setBusy(true);onError("");try{const response=await fetch(`/api/incidents/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expectedRevision:item.revision,idempotencyKey:crypto.randomUUID(),occurredAt:current.occurredAt,category:current.category,narrative:text,reason,context:current.context,externalParties:current.externalParties})});const j=await response.json();if(!response.ok){onError(j.error??"Correction not recorded");return;}if(await onSaved())setOpen(false);else onError("Correction accepted, but the current Incident could not be refreshed. Refresh before acting again.");}catch{onError("Correction not confirmed. Refresh the Incident before retrying.");}finally{setBusy(false);}}}><label>Corrected factual description<textarea required minLength={10} maxLength={6000} value={text} onChange={e=>setText(e.target.value)} /></label><label>Reason for correction<textarea required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="incident-primary" disabled={busy}>{busy?"Saving correction…":"Save correction"}</button></form>}</section>;
}
