"use client";
import { useEffect, useState } from "react";
type Choice={id:string;name:string;siteName?:string;role?:string};
type Grant={id:string;personId:string;personName:string;kind:string;from:string;until:string;reason:string;revokedAt?:string};
const dateTime=(v:string)=>new Date(v).toLocaleString("en-GB",{timeZone:"Europe/London",dateStyle:"medium",timeStyle:"short"});
export function SiteBookAccess(){
 const [services,setServices]=useState<Choice[]>([]),[people,setPeople]=useState<Choice[]>([]),[service,setService]=useState(""),[person,setPerson]=useState(""),[kind,setKind]=useState("CONTRIBUTOR"),[from,setFrom]=useState(""),[until,setUntil]=useState(""),[reason,setReason]=useState(""),[grants,setGrants]=useState<Grant[]>([]),[error,setError]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;void fetch("/api/site-book/grants",{cache:"no-store"}).then(async r=>({r,j:await r.json()})).then(({r,j})=>{if(!live)return;if(!r.ok)throw new Error(j.error);setServices(j.choices?.services??[]);setPeople(j.choices?.people??[])}).catch(e=>{if(live)setError(e.message??"Access choices unavailable")});return()=>{live=false}},[]);
 async function load(serviceId:string){if(!serviceId)return;const r=await fetch(`/api/site-book/grants?serviceId=${serviceId}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error??"Grants unavailable");setGrants(j.grants??[])}
 async function send(payload:Record<string,unknown>){setBusy(true);setError("");setStatus("");try{const r=await fetch("/api/site-book/grants",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error??"Grant change not accepted");setStatus(payload.action==="issue"?"Grant issued and audited.":"Grant revoked and audited.");await load(service);if(payload.action==="issue")setReason("")}catch(e){setError(e instanceof Error?e.message:"Grant change not accepted")}finally{setBusy(false)}}
 return <div className="site-book-grid"><section className="site-book-card"><h2>Grant access</h2><p className="site-book-warning">A contributor grant permits routine book access during its finite window without a shift allocation. A manager grant requires an active Operations role. Neither grant permits Incident, patrol or private personnel access.</p><form className="site-book-form" onSubmit={e=>{e.preventDefault();send({action:"issue",serviceId:service,personId:person,kind,from:new Date(from).toISOString(),until:new Date(until).toISOString(),reason})}}><label>Exact Site Service<select required value={service} onChange={e=>{setService(e.target.value);setGrants([]);void load(e.target.value).catch(x=>setError(x.message))}}><option value="">Choose Service</option>{services.map(s=><option key={s.id} value={s.id}>{s.siteName} · {s.name}</option>)}</select></label><label>Person<select required value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose Person</option>{people.filter(p=>kind==="MANAGER"?p.role==="OPERATIONS":p.role==="SECURITY_STAFF").map(p=><option key={p.id} value={p.id}>{p.name} · {p.role}</option>)}</select></label><label>Grant kind<select value={kind} onChange={e=>{setKind(e.target.value);setPerson("")}}><option value="CONTRIBUTOR">Unallocated Staff contributor</option><option value="MANAGER">Operations book manager</option></select></label><div className="site-book-row"><label>From<input required type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Until<input required type="datetime-local" value={until} onChange={e=>setUntil(e.target.value)}/></label></div><label>Reason<input required minLength={3} maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="site-book-primary" disabled={busy}>Issue finite grant</button></form>{error&&<p className="site-book-alert" role="alert">{error}</p>}{status&&<p className="site-book-status" role="status">{status}</p>}</section><section className="site-book-card"><h2>Grants for this Service</h2>{grants.length?<ul className="site-book-list">{grants.map(g=><li key={g.id}><strong>{g.personName} · {g.kind}</strong><small>{dateTime(g.from)} – {dateTime(g.until)}{g.revokedAt?` · Revoked ${dateTime(g.revokedAt)}`:""}</small><p>{g.reason}</p>{!g.revokedAt&&<button className="site-book-secondary" disabled={busy} onClick={()=>{const why=window.prompt("Reason for revocation (at least 3 characters)");if(why)send({action:"revoke",grantId:g.id,reason:why})}}>Revoke with reason</button>}</li>)}</ul>:<p className="site-book-empty">Choose a Service to inspect its grants.</p>}</section></div>;
}
