"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { addCivilDays } from "@/lib/events/workforce-week";
import { buildWorkforceReturn, type WorkforceReturnState } from "@/lib/events/workforce-navigation";
import s from "./workforce-planner.module.css";

type Allocation = { id:string; person_name:string; status:string; availability:string; availability_conflict:string|null; allocation_clash:boolean; approved_time_away_conflict:boolean };
type Duty = { source:"EVENT"|"SITE_SHIFT"; requirement_id:string; event_id:string|null; service_id:string|null; site_id:string; service_date:string; report_at:string; shift_starts_at:string; shift_ends_at:string; required_quantity:number; area_label:string; role_name:string; event_name:string; site_name:string; client_name:string; allocated:number; accepted:number; remaining:number; awaiting_response:number; unavailable_conflicts:number; coverage_conflicts:number; not_declared:number; partial_coverage:number; clashes:number; approved_time_away_conflicts:number; allocations:Allocation[] };
type Schedule = { static_horizon_covered:boolean; total_lines:number; totals:{required:number;allocated:number;accepted:number;remaining:number;availability_conflicts:number;approved_time_away_conflicts:number;allocation_clashes:number};items:Duty[] };
type Choice = { id:string;name:string };
type Choices = { events:Choice[];sites:Choice[];clients:string[];roles:Choice[] };
type Filters = { client:string;site:string;event:string;role:string;open:boolean };
const emptyFilters:Filters = { client:"",site:"",event:"",role:"",open:false };
const dateLabel=(date:string,weekday:"long"|"short"="short")=>new Date(`${date}T12:00:00Z`).toLocaleDateString("en-GB",{timeZone:"Europe/London",weekday,day:"numeric",month:"short"});
const time=(date:string)=>new Date(date).toLocaleString("en-GB",{timeZone:"Europe/London",weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"});
const hour=(date:string)=>new Date(date).toLocaleTimeString("en-GB",{timeZone:"Europe/London",hour:"2-digit",minute:"2-digit"});
const londonDate=(date:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(date));
const sourceLabel=(d:Duty)=>d.source==="EVENT"?"Event":"Site Shift";
const sourceHref=(d:Duty)=>d.source==="EVENT"?`/events/${d.event_id}?requirement=${d.requirement_id}`:`/sites/${d.site_id}/services/${d.service_id}?demand=${d.requirement_id}`;
const read=async(path:string)=>{const response=await fetch(path,{cache:"no-store"});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error??"Workforce read unavailable");return result;};
const key=(d:Duty)=>`${d.source}:${d.requirement_id}`;

function DutyButton({duty,onOpen,compact=false}:{duty:Duty;onOpen:(d:Duty)=>void;compact?:boolean}) {
  return <button type="button" className={`${s.duty} ${compact?s.compact:""}`} onClick={()=>onOpen(duty)} aria-label={`${sourceLabel(duty)}, ${duty.client_name}, ${duty.site_name}, ${duty.event_name}, ${duty.role_name}, ${duty.area_label}, ${duty.remaining} open, ${duty.awaiting_response} awaiting response; view duty`}>
    {!compact&&<><span className={s.source}>{sourceLabel(duty)}</span><strong>{duty.role_name}{duty.area_label?` · ${duty.area_label}`:""}</strong><span>{duty.event_name} · {duty.site_name}</span></>}
    <span className={s.counts}>{compact?<>{hour(duty.shift_starts_at)}{londonDate(duty.shift_ends_at)>londonDate(duty.shift_starts_at)?" → next day":""}<br/>{duty.required_quantity} req · {duty.remaining} open<br/>{duty.awaiting_response} await · {duty.accepted} acc</>:<>{duty.required_quantity} required · {duty.remaining} open · {duty.awaiting_response} awaiting · {duty.accepted} accepted</>}</span>
    {!compact&&<span>Report {time(duty.report_at)} · Shift {time(duty.shift_starts_at)} → {time(duty.shift_ends_at)}</span>}
    {duty.allocations.length>0&&<span className={s.names}>{duty.allocations.slice(0,2).map(a=>`${a.person_name} (${a.status==="ACCEPTED"?"accepted":"awaiting"})`).join(" · ")}{duty.allocations.length>2?` · +${duty.allocations.length-2}`:""}</span>}
    {(duty.unavailable_conflicts+duty.coverage_conflicts+duty.approved_time_away_conflicts+duty.clashes)>0&&<span className={s.attention}>Review availability, time away or clash</span>}
  </button>;
}
function GroupedDuties({duties,onOpen}:{duties:Duty[];onOpen:(d:Duty)=>void}) {
  const clients=[...new Set(duties.map(d=>d.client_name))];
  return <div className={s.groups}>{clients.map(client=><section key={client} className={s.clientGroup}><h3>{client}</h3>{[...new Set(duties.filter(d=>d.client_name===client).map(d=>d.site_name))].map(site=><div key={site} className={s.siteGroup}><h4>{site}</h4>{[...new Set(duties.filter(d=>d.client_name===client&&d.site_name===site).map(d=>`${d.source}:${d.event_id??d.service_id}`))].map(group=>{const rows=duties.filter(d=>d.client_name===client&&d.site_name===site&&`${d.source}:${d.event_id??d.service_id}`===group);return <div key={group} className={s.sourceGroup}><p><span className={s.source}>{sourceLabel(rows[0])}</span> {rows[0].event_name}</p>{rows.map(d=><DutyButton key={key(d)} duty={d} onOpen={onOpen} />)}</div>;})}</div>)}</section>)}</div>;
}

export function WorkforcePlanner({week,selectedDay,onSelectDay,initial={}}:{week:string;selectedDay:string;onSelectDay:(day:string)=>void;initial?:Partial<WorkforceReturnState>}) {
  const [filters,setFilters]=useState<Filters>(()=>({client:initial.client??"",site:initial.site??"",event:initial.event??"",role:initial.role??"",open:initial.open??false}));
  const [view,setView]=useState<"matrix"|"day">("matrix");
  const [schedule,setSchedule]=useState<Schedule|null>(null);
  const [choices,setChoices]=useState<Choices|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [selected,setSelected]=useState<Duty|null>(null);
  const seq=useRef(0);
  const initialDuty=useRef(initial.duty&&initial.source?`${initial.source}:${initial.duty}`:null);
  const [returnMissing,setReturnMissing]=useState(false);
  const days=useMemo(()=>Array.from({length:7},(_,i)=>addCivilDays(week,i)),[week]);
  const load=useCallback(async()=>{const current=++seq.current;setLoading(true);setError("");const q=new URLSearchParams({week,offset:"0"});for(const field of ["client","site","event","role"] as const){if(filters[field])q.set(field,filters[field]);}if(filters.open)q.set("gaps","true");try{const result=await read(`/api/workforce?${q}`);const first:Schedule=result.schedule;if(first.total_lines>2000)throw new Error("This week has too many duty lines for the current planner read. Narrow the filters or use the source workflow.");const offsets=Array.from({length:Math.ceil(first.total_lines/40)-1},(_,i)=>(i+1)*40);const rest=await Promise.all(offsets.map(async offset=>{const copy=new URLSearchParams(q);copy.set("offset",String(offset));const response=await read(`/api/workforce?${copy}`);return response.schedule as Schedule;}));if(rest.some(page=>page.total_lines!==first.total_lines||JSON.stringify(page.totals)!==JSON.stringify(first.totals)))throw new Error("Coverage changed while loading the week. Refresh to read the current source state.");const full={...first,items:[...first.items,...rest.flatMap(page=>page.items)]};if(full.items.length!==full.total_lines||new Set(full.items.map(key)).size!==full.total_lines)throw new Error("The complete authorised week could not be read consistently. Refresh to try again.");if(current!==seq.current)return;setSchedule(full);if(initialDuty.current){const exact=full.items.find((d:Duty)=>key(d)===initialDuty.current)??null;setSelected(exact);setReturnMissing(!exact);initialDuty.current=null;}else setSelected(previous=>previous?full.items.find((d:Duty)=>key(d)===key(previous))??null:null);try{const c=await read(`/api/workforce/choices?week=${week}`);if(current===seq.current)setChoices(c.choices);}catch{if(current===seq.current)setChoices(null);}}
    catch(caught){if(current===seq.current){setSchedule(null);setSelected(null);setError(caught instanceof Error?caught.message:"Workforce read unavailable");}}finally{if(current===seq.current)setLoading(false);}},[week,filters]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{const refresh=()=>{if(document.visibilityState==="visible")void load();};document.addEventListener("visibilitychange",refresh);window.addEventListener("focus",refresh);return()=>{document.removeEventListener("visibilitychange",refresh);window.removeEventListener("focus",refresh);};},[load]);
  function change<K extends keyof Filters>(field:K,value:Filters[K]){setFilters(old=>({...old,[field]:value}));}
  const page=schedule?.items??[];const totals=schedule?.totals;const hasFilters=Boolean(filters.client||filters.site||filters.event||filters.role||filters.open);
  const clients=[...new Set(page.map(d=>d.client_name))].sort();
  const sites=[...new Map(page.map(d=>[d.site_id,{id:d.site_id,name:d.site_name,client:d.client_name}])).values()].sort((a,b)=>a.name.localeCompare(b.name)||a.client.localeCompare(b.client));
  const events=[...new Map(page.filter(d=>d.source==="EVENT"&&d.event_id).map(d=>[d.event_id!,{id:d.event_id!,name:`${d.event_name} · ${d.site_name} · ${d.client_name}`}])).values()].sort((a,b)=>a.name.localeCompare(b.name));
  const exactSourceHref=(d:Duty)=>{const url=new URL(sourceHref(d),"http://kss.local");url.searchParams.set("returnTo",buildWorkforceReturn({week,day:selectedDay,client:filters.client,site:filters.site,event:filters.event,role:filters.role,open:filters.open,duty:d.requirement_id,source:d.source}));url.searchParams.set("sourceWeek",week);return `${url.pathname}${url.search}`;};
  return <section className={s.planner} aria-label="Workforce planning">
    <div className={s.heading}><div><p className={s.eyebrow}>Coverage workspace · synthetic development</p><h2>Workforce planning</h2><p>Event and Site Shift duties share a view; each action stays with its source.</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}>Refresh</Button></div>
    <div className={s.filters} aria-label="Planning filters"><label>Client<select value={filters.client} onChange={e=>change("client",e.target.value)}><option value="">All clients</option>{clients.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label>Site<select value={filters.site} onChange={e=>change("site",e.target.value)}><option value="">All sites</option>{sites.map(v=><option key={v.id} value={v.id}>{v.name} · {v.client}</option>)}</select></label><label>Event<select value={filters.event} onChange={e=>change("event",e.target.value)}><option value="">All Events and Site Shifts</option>{events.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Role<select value={filters.role} onChange={e=>change("role",e.target.value)}><option value="">All roles</option>{choices?.roles.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label className={s.check}><input type="checkbox" checked={filters.open} onChange={e=>change("open",e.target.checked)} /> Open positions</label>{hasFilters&&<Button variant="ghost" onClick={()=>setFilters(emptyFilters)}>Clear</Button>}</div>
    {filters.event&&<p className={s.note}>Event filter shows the selected Event only; Site Shift duties are outside that filter.</p>}
    {error&&<p role="alert" className={s.error}>{error} <Button variant="outline" onClick={()=>void load()}>Retry</Button></p>}
    {returnMissing&&<p role="status" className={s.note}>The selected duty is no longer in this authorised week and filter. Review the current source or adjust the filters.</p>}
    {loading?<p role="status" className={s.note}>Loading authorised coverage…</p>:schedule&&<>
      <div className={s.summary} aria-label="Filtered week coverage totals">{[["Required",totals?.required],["Allocated",totals?.allocated],["Awaiting response",(totals?.allocated??0)-(totals?.accepted??0)],["Accepted",totals?.accepted],["Open",totals?.remaining]].map(([label,value])=><div key={String(label)}><strong>{value}</strong><span>{label}</span></div>)}</div>
      {!schedule.static_horizon_covered&&<p className={s.error}>This week extends beyond the generated Site Shift horizon. Missing Site Shift demand may be incomplete; reconcile the source service.</p>}
      <div className={s.viewBar}><div className={s.viewSwitch} aria-label="Planning view"><Button variant={view==="matrix"?"default":"outline"} onClick={()=>setView("matrix")}>Week matrix</Button><Button variant={view==="day"?"default":"outline"} onClick={()=>setView("day")}>Day planner</Button></div><span>{schedule.total_lines} duty lines</span></div>
      <div className={s.weekStrip} aria-label="Select planning day">{days.map(day=><button key={day} type="button" className={day===selectedDay?s.selectedDay:""} aria-pressed={day===selectedDay} onClick={()=>onSelectDay(day)}><span>{dateLabel(day)}</span></button>)}</div>
      {schedule.total_lines===0?<p className={s.empty}>No authorised duty lines match this week and filter.</p>:<>
        <div className={`${s.matrix} ${view==="day"?s.matrixHidden:""}`} aria-label="Seven-day coverage matrix"><div className={s.matrixHead}><span>Client → Site → source → duty</span>{days.map(day=><strong key={day}>{dateLabel(day)}</strong>)}</div>{[...new Set(page.map(d=>d.client_name))].map(client=><div key={client} className={s.matrixClient}><h3>{client}</h3>{[...new Set(page.filter(d=>d.client_name===client).map(d=>d.site_name))].map(site=><div key={site}><h4>{site}</h4>{[...new Set(page.filter(d=>d.client_name===client&&d.site_name===site).map(d=>`${d.source}:${d.event_id??d.service_id}`))].map(group=>{const rows=page.filter(d=>d.client_name===client&&d.site_name===site&&`${d.source}:${d.event_id??d.service_id}`===group);return <div key={group} className={s.matrixGroup}><p><span className={s.source}>{sourceLabel(rows[0])}</span> {rows[0].event_name}</p>{[...new Set(rows.map(d=>`${d.role_name}:${d.area_label}`))].map(role=>{const roleRows=rows.filter(d=>`${d.role_name}:${d.area_label}`===role);return <div key={role} className={s.matrixRow}><strong>{roleRows[0].role_name}{roleRows[0].area_label?` · ${roleRows[0].area_label}`:""}</strong>{days.map(day=><div key={day} className={s.matrixCell}>{roleRows.filter(d=>d.service_date===day).map(d=><DutyButton key={key(d)} duty={d} onOpen={setSelected} compact />)}</div>)}</div>;})}</div>;})}</div>)}</div>)}</div>
        <div className={`${s.dayPlanner} ${view==="day"?s.dayShown:""}`}><h3>{dateLabel(selectedDay,"long")}</h3>{page.filter(d=>d.service_date===selectedDay).length?<GroupedDuties duties={page.filter(d=>d.service_date===selectedDay)} onOpen={setSelected}/>:<p className={s.empty}>No duties on this day in the current page.</p>}</div>
      </>}
      <p className={s.note}>Counts and duties cover the same authorised week and filters.</p>
    </>}
    <Sheet open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className={s.panel}><SheetHeader><p className={s.eyebrow}>{selected&&sourceLabel(selected)} · exact source duty</p><SheetTitle>{selected?.role_name}{selected?.area_label?` · ${selected.area_label}`:""}</SheetTitle><SheetDescription>{selected?.client_name} · {selected?.site_name} · {selected?.event_name}</SheetDescription></SheetHeader>{selected&&<div className={s.panelBody}><p><strong>Duty date</strong> {dateLabel(selected.service_date,"long")}</p><p><strong>Report</strong> {time(selected.report_at)}</p><p><strong>Shift</strong> {time(selected.shift_starts_at)} → {time(selected.shift_ends_at)}</p><div className={s.panelCounts}><span>Required <strong>{selected.required_quantity}</strong></span><span>Allocated <strong>{selected.allocated}</strong></span><span>Awaiting <strong>{selected.awaiting_response}</strong></span><span>Accepted <strong>{selected.accepted}</strong></span><span>Remaining <strong>{selected.remaining}</strong></span></div><h3>Current allocations</h3>{selected.allocations.length?<ul>{selected.allocations.map(a=><li key={a.id}><strong>{a.person_name}</strong> · {a.status==="ACCEPTED"?"Accepted":"Allocated · awaiting response"}{a.availability_conflict&&<> · Availability: {a.availability_conflict.replaceAll("_"," ").toLowerCase()}</>}{a.approved_time_away_conflict&&<> · Approved Time Away conflict</>}{a.allocation_clash&&<> · Allocation clash</>}</li>)}</ul>:<p>No current allocations. {selected.remaining} open position{selected.remaining===1?"":"s"}. Unfilled demand is not published Staff work.</p>}<h3>Attention</h3><ul><li>{selected.unavailable_conflicts} declared unavailable conflict{selected.unavailable_conflicts===1?"":"s"}</li><li>{selected.coverage_conflicts} changed coverage warning{selected.coverage_conflicts===1?"":"s"}</li><li>{selected.not_declared} missing declaration{selected.not_declared===1?"":"s"}</li><li>{selected.partial_coverage} partial coverage warning{selected.partial_coverage===1?"":"s"}</li><li>{selected.approved_time_away_conflicts} approved Time Away conflict{selected.approved_time_away_conflicts===1?"":"s"}</li><li>{selected.clashes} allocation clash{selected.clashes===1?"":"es"}</li></ul><Link className={s.sourceLink} href={exactSourceHref(selected)}>{selected.remaining>0?"Review candidates and manage requirement":"Manage exact source duty"}</Link><p className={s.note}>Candidate review and allocation changes use the source workflow and its guarded server readback.</p></div>}</SheetContent></Sheet>
  </section>;
}
